### ISSUE TITLE
Maintain this list in a way that's accessible by our entire stack

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-looking-for#3]
clippings - It points to epaper

**Comment by matthew-andrews** [comment]
fix it

**Comment by matthew-andrews** [comment]
:)

**Comment by wheresrhys** [comment]
So, to fix this properly I'm thinking a bertha spreadsheet of these pages, It can then be polled by mustang for search suggestions, and this module can provide some middleware to poll bertha and write the result to res.locals

**Comment by matthew-andrews** [comment]
:+1:

**Comment by matthew-andrews** [comment]
this probably is in the category of simple redirects…… and you wouldn't want every redirect there to appear on looking for or search suggestions:-
https://github.com/Financial-Times/next-redirector/blob/master/server/controllers/simple-mapping.js


I guess your spreadsheet could have:
- human readable name (for typing into search or clicking on on looking for)
- trackable id (for looking for so we can see what people click)
- true/false for whether to include in the ui (search sugg & looking for), otherwise a plain 302
- path to match (for redirector)
- destination url

**Comment by matthew-andrews** [comment]
^^ given that doens't feel like there's *too* much overlap with redirector.  might be easier to manage if have two sheets (one for looking fors & search sugg and then one for plain 302s) and redirectors could read both and concat the results togehter.
